version: '3.0'
services:
  trello_com:
    image: nginx:1.15.10
    volumes:
      - ./fixtures/ok.html:/usr/share/nginx/html/ok.html 
      - ./fixtures:/etc/nginx

  trello_proxy:
    image: nginx:1.15.10
    volumes:
      - ./nginx.conf:/tmp/nginx.tmpl
      - ./proxy.conf:/tmp/proxy.tmpl
    ports:
      - 8080:80
    command: >
      /bin/sh -eux -c 
        "sed -e 's/{{port}}/80/g'< \
          /tmp/nginx.tmpl > /etc/nginx/nginx.conf && \
        sed -e 's|https://trello.com|http://trello_com|g' < \
          /tmp/proxy.tmpl > /etc/nginx/proxy.conf && \
        exec nginx;"

networks:
  default:
    ipam:
      driver: default
      config:
        - subnet: 172.32.0.0/16
    

